### ISSUE TITLE
💄 Let's all get PRETTY 💄

### ISSUE THREAD

**Issue by jbampton** [One-Language/One#103]
https://prettier.io/

https://prettier.io/docs/en/precommit.html

<img width="1363" alt="Screen Shot 2021-06-05 at 4 34 35 pm" src="https://user-images.githubusercontent.com/418747/120882621-5e651980-c61c-11eb-9401-9178bd94ae85.png">

<img width="1393" alt="Screen Shot 2021-06-05 at 4 34 30 pm" src="https://user-images.githubusercontent.com/418747/120882634-6755eb00-c61c-11eb-9143-7832446de043.png">

<img width="1379" alt="Screen Shot 2021-06-05 at 4 34 45 pm" src="https://user-images.githubusercontent.com/418747/120882644-7341ad00-c61c-11eb-871e-c3b0fc613e38.png">

**Comment by BaseMax** [comment]
> code formatter
But We already have `clang-format`. Can you explain a bit more? @jbampton

**Comment by BaseMax** [comment]
C/C++ not supported, so probably we have to skip it.

**Comment by BaseMax** [comment]
John, This support JSX, You can add this to website repo.

**Comment by jbampton** [comment]
Prettier also support Markdown and some others could come in handy too.  

Auto formatting.

I am going to add it now to `One`.  Thank you !!

**Comment by jbampton** [comment]
Done
