### ISSUE TITLE
🗄️ Monorepo for One must start now by including the `Document` site 🗄️

### ISSUE THREAD

**Issue by jbampton** [One-Language/One#106]
**Is your feature request related to a problem? Please describe.**

In version control systems, a monorepo is a software development strategy where code for many projects is stored in the same repository. As of 2017, various forms of this software engineering practice were over two decades old, but the general concept had only recently been named.

**Describe the solution you'd like**

Auto deploys and pull request deployment previews.

Able to maintain different documentation versions.

https://readthedocs.org/

**Describe alternatives you've considered**

Waste time juggling repos.

**Additional context**

Free hosting and a new environment to show off the `One` Power.

**Comment by BaseMax** [comment]
We already have a repository for documentation. https://github.com/One-Language/Document
it's up and launches with GitHub pages.
https://docs.onelang.org/#/en/

**Comment by BaseMax** [comment]
If possible, explain why we should use https://readthedocs.org/? @jbampton
