### ISSUE TITLE
[Join] Documentation team

### ISSUE THREAD

**Issue by basalumutgazi** [One-Language/One#114]
Hi, One language Team;
I'm here to tell you I'm interested in the project and want to be a part of this compiler to help and participate in this open-source project.

## Introduction
Hello, my name is Umut and I am from Turkey. I am a student and I really love being a part of programming organizations like this. My field of study is related to languages. Thank's to that, I am good at writing and translating.

## Your correct role

I'm a Bachelor's student of Applied Linguistics and Comparative Foreign Languages.
I also work as a freelance translator and writer.
I know how to use Markdown and GitHub.

## Timezone

Istanbul,Turkey, UTC/GMT +3

## Language Proficiency

- **Turkish**: Expert (Native)
- **English**: Expert
- **French**: Intermediate

## Programming/IT knowledge

Tell us more about your Programming/IT knowledge:
I am learning Python and I have written some basic programs. I know how to use Git and Markdown files. I help some GitHub organizations in their article writing and publishing process. I learn quickly and I am learning new things every day.

Tell us your opinion about "One language" and create a new language:
I've talked to @BaseMax and the aims of the project really impressed me. Loved the idea of creating a new language for all kinds of tasks.

-----------
Best Regards;
Umut

**Comment by BaseMax** [comment]
Welcome, Umut.

**Comment by jbampton** [comment]
Welcome mate !!
