### ISSUE TITLE
🖼️ LOGO of The One Programming Language 🖼️

### ISSUE THREAD

**Issue by BaseMax** [One-Language/One#116]
Hi there;
![The One Programming Language](https://user-images.githubusercontent.com/2658040/121019253-80919f80-c7b4-11eb-9723-b9afcae42801.png)

It's designed by **Javad Sabet** (a.k.a Jas)

He is my friend and was my early coworker in this project years ago.
He believes 1 or @ character is good idea for the LOGO of this project.

**Comment by BaseMax** [comment]
But today, Dear Umut shared a new idea and cool logo with me.
I think it's good too.
I ask the Umut to share all of the logo files here.

**Comment by basalumutgazi** [comment]
I have 2 different versions. Made everything you wanted for both of them. Thank you!

![2_black_stroke](https://user-images.githubusercontent.com/81925269/121022212-d103ff80-c7aa-11eb-960f-7a8e14e6a218.png)
![2_white_stroke](https://user-images.githubusercontent.com/81925269/121022216-d19c9600-c7aa-11eb-9fe3-70546f07e44a.png)
![2_white](https://user-images.githubusercontent.com/81925269/121022217-d2352c80-c7aa-11eb-8abc-29b2f2311ff7.png)
![2_black](https://user-images.githubusercontent.com/81925269/121022219-d2352c80-c7aa-11eb-9ba1-d8163b92a2c1.png)
![1_black](https://user-images.githubusercontent.com/81925269/121022223-d2352c80-c7aa-11eb-8186-d499a6073387.png)
![1_black_stroke](https://user-images.githubusercontent.com/81925269/121022228-d2cdc300-c7aa-11eb-8799-ba90f0a0031b.png)
![1_white_stroke](https://user-images.githubusercontent.com/81925269/121022233-d2cdc300-c7aa-11eb-8e1f-5bb2e754effb.png)
![1_white](https://user-images.githubusercontent.com/81925269/121022235-d3665980-c7aa-11eb-8f1f-a04147027143.png)

**Comment by ajakov** [comment]
> ![2_black_stroke](https://user-images.githubusercontent.com/81925269/121022212-d103ff80-c7aa-11eb-960f-7a8e14e6a218.png)

I like this one the most

**Comment by jbampton** [comment]
Great work all !!!  Done !!
