### ISSUE TITLE
Would love an invite to the team 

### ISSUE THREAD

**Issue by jbampton** [One-Language/One#13]
Hey @BaseMax would love to join and help out where I can 👍 

Since we worked on Donya we make a good team :)

**Comment by midopooler** [comment]
Hey @BaseMax , I would also like to join this organisation. Can you let me in?

**Comment by shivaylamba** [comment]
Hey @BaseMax , I would also like to join this organisation. Can you let me in?

**Comment by riturajjain2000** [comment]
Hello @BaseMax , my name is Rituraj. I am from India.
I Would like to join this organization.
I love to contribute to open source and will love to contribute to this organization.
