### ISSUE TITLE
[Join] Website team

### ISSUE THREAD

**Issue by shannon-nz** [One-Language/One#145]
Hi, One language Team;
I'm here to tell you I'm interested in the project and want to be a part of this compiler to help and participate in this open-source project.

## Introduction
I'm Shannon, a Full Stack Developer.
More info about me can be found here <a href="https://github.com/shannon-nz">https://github.com/shannon-nz</a>

## Timezone
NZT - New Zealand Time / Auckland

## Programming experience
More info about me can be found here <a href="https://github.com/shannon-nz">https://github.com/shannon-nz</a>

## Front-end experience
More info about me can be found here <a href="https://github.com/shannon-nz">https://github.com/shannon-nz</a>

**Comment by jbampton** [comment]
Invite sent.  Welcome
