### ISSUE TITLE
Add GitHub Super Linter

### ISSUE THREAD

**Issue by jbampton** [One-Language/One#15]
Hey Max,

I am going to add the Super Linter today as my first task.

https://github.com/github/super-linter

Hope you are doing well today.

Thanks.

**Comment by BaseMax** [comment]
Thank you John.

**Comment by BaseMax** [comment]
It will be useful for this project to auto lint and beautifly `*.c` files.

**Comment by BaseMax** [comment]
link: https://github.com/One-Language/One/pull/21
