### ISSUE TITLE
[Join] Website team

### ISSUE THREAD

**Issue by JayantGoel001** [One-Language/One#154]
Hi, One language Team;
I'm here to tell you I'm interested in the project and want to be a part of this compiler to help and participate in this open-source project.

## Introduction

I am Jayant Goel. 
I like Android, Web Development, and Data Science.
## Your correct role

I'm a Bachelor's student of computer science at the Jaypee Institute Of Information technology.
And Have a part-time job as an SDE Intern at TalentDecrypt in India.

## Timezone

Kolkata, India; UTC/GMT +5:30 hours

## Programming experience

List of languages with experience level:

- **HTML5**: 2 years experience
- **CSS3**: 2 years experience
- **Vanilla JS**: Just for fun to write 3-5 scripts without professional experience (And tell us about libraries you have worked on. e.g: Axios, and every library you worked in at JS.)
- **ReactJS**: Just for personal needs (and tell us about libraries you have worked on)
- **VueJS**: Just for personal needs (and tell us about libraries you have worked on)

## Front-end experience

Tell us about your experience or your fun projects about website design or programming:
https://github.com/JayantGoel001

Do you know about ReactJS and VueJs:

Do you know about NextJS:

Do you know about PureJS Es6:

Do you know about jQuery:

Do you able to design the UI of the website pages?

What design software you are familiar with and can open and use?

Tell us your opinion about "One language" and create a new language:

-----------

Best Regards;

**Comment by jbampton** [comment]
Invite is now sent.  Welcome mate 💯
