### ISSUE TITLE
I wanna join the One-Language Org !

### ISSUE THREAD

**Issue by Majalian** [One-Language/One#16]
Hey BaseMax 
I'm @jbampton friend and would like to join your org!
One Language \m/

**Comment by BaseMax** [comment]
Hey Mujahid
Thank you, Do you have experience in **C programming**?

**Comment by Majalian** [comment]
Hey Max
Unfortunately I don't.
but my friend @jbampton and I were working together on many projects regarding translation into more languages, it'd be a great step towards internationalizing and expanding your reach into more audience. I will provide fast and accurate translation for README and FAQ and any other docs that could potentially benefits you on the short or long run..
thanks to our friend John, I was able to be properly introduced to GitHub and Git which I find so cool and fun to use!

If You ever interested or in need to translate Arabic-English and vice-versa, I'm your guy!

Thank You.
