### ISSUE TITLE
I want to join the One-Language Org !!

### ISSUE THREAD

**Issue by basalumutgazi** [One-Language/One#17]
Hi! 
I'm a friend of @jbampton and I translate into Turkish for him. There are 96 million speakers of Turkish around the world according to Wikipedia (https://tr.wikipedia.org/wiki/T%C3%BCrk%C3%A7e) So, I want to be a part of your team and do translations for you. 
Thank you

**Comment by BaseMax** [comment]
Thanks.
Welcome basalumutgazi. What's your Name?

**Comment by basalumutgazi** [comment]
Hi BaseMax,
My name is Umut.
Thanks.
