### ISSUE TITLE
Complete Persian/FA readme file and solve minor problems

### ISSUE THREAD

**Issue by BaseMax** [One-Language/One#171]
Need a native Persian person or Iranian open-source lover

I will do this probably...

https://github.com/One-Language/One/blob/master/README_FA.md

**Comment by BaseMax** [comment]
@amir-shiati accepted this and will complete it ASAP.

**Comment by BaseMax** [comment]
John, please assign this issue to Dear "amir-shiati".
Thanks in advance.

**Comment by amir-shiati** [comment]
Hey guys.
@BaseMax @jbampton Done! #181
