### ISSUE TITLE
I wanna join One-Language GitHub Organization !

### ISSUE THREAD

**Issue by ladyjheng26** [One-Language/One#18]
Hello! I am a friend of @jbampton and I do Filipino translations for him. As of today, there are about 24.2 million speakers of Tagalog or the Filipino language worldwide. It is even the sixth most-spoken language in the US. I would really love to be part of your organizations and I look forward to working with you.

**Comment by BaseMax** [comment]
Welcome Ladylyn.

**Comment by ladyjheng26** [comment]
Thank you BaseMax.
