### ISSUE TITLE
I want to join the One-Language organization

### ISSUE THREAD

**Issue by VictorAraica** [One-Language/One#19]
Hello,
I'm also a friend of John Bampton, at the time I'm working and studying so I don't have a lot of free time, but i still want to join your team. My native language is Spanish and I know how to use Python, Java, HTML, CSS, JavaScript, Tailwind, React and nodejs. I don't know much about C lang but i would really like to learn about it over time, and i think this is a great opportunity for that.
Thank you.

**Comment by BaseMax** [comment]
Welcome Victor.

**Comment by BaseMax** [comment]
Hi Victor
Thanks, What's your job and role in the company?
I think you can prepare the site for this project.

**Comment by jbampton** [comment]
Hey Max,

@VictorAraica doesn't have much time right now.  But he is still interested.

If you want I can look over the website code ?  

I have worked on a lot of websites but its not my best skill.

Sorry I am a bit behind today a friend came over before to cook dinner.

Thank you.

**Comment by BaseMax** [comment]
You are welcome. no problem.
We will need website in next step, not right now. So probably you can a few some time later. :+1:
