### ISSUE TITLE
🚢 Docker to build and run test file 🛳️

### ISSUE THREAD

**Issue by BaseMax** [One-Language/One#193]

**Comment by abdorah** [comment]
Hello, I think that to make this in a proper way we need to agree exactly on the basic things that define our image. The first thing is that what we are trying to make is a `Dockerfile` with a base image of production and a set of tools that we need to include. To clearly explain what I meant I wrote this simple example as a first attempt that we can discuss:
``` Dockerfile
FROM alpine:latest
LABEL One PROGRAMING LANGUAGE

ARG LLVM_VERSION=7.0.0

RUN apk --no-cache add \
	autoconf \
	automake \
	cmake \
	freetype-dev \
	g++ \
	gcc \
	libxml2-dev \
	linux-headers \
	make \
	musl-dev \
	ncurses-dev \
	python2 

COPY install_llvm.sh /
RUN ./install_llvm.sh ${LLVM_VERSION} && rm install_llvm.sh

ENV CXX=clang++
ENV CC=clang

RUN pip install pre-commit

WORKDIR /One

COPY src/ ./src/
COPY test/ ./test/

RUN cd src/parser
RUN ./build.sh
RUN cd ..

RUN cd lexer/tokenizer
RUN ./build.sh
RUN cd ..

RUN ./build.sh
RUN ./test.sh
RUN cd ..

RUN cd ..
RUN cd test
CMD ["./build.sh"]
```

**Comment by BaseMax** [comment]
Thanks, Please send a PR for this one. @abdorah 

Note: We use latest version of LLVM. So 12

**Comment by BaseMax** [comment]
`Docekrfile` and `docker-compose.yml`.
We already have a empty `docker-compose.yml` file but we need ti fill it or remove.

**Comment by BaseMax** [comment]
PR sent by Kotbi at https://github.com/One-Language/One/pull/202. (link to PR)

**Comment by abdorah** [comment]
Hey, @BaseMax I have changed the code that I used for the previous PR. Now there is no need to have an `install_llvm.sh` file all we need is a `Dockerfile` and `docker-compose.yml`.

**Comment by BaseMax** [comment]
Thanks 👍
