### ISSUE TITLE
Request for joining the Org

### ISSUE THREAD

**Issue by riturajjain2000** [One-Language/One#20]
Rituraj here form India , would love to join the org!

**Comment by BaseMax** [comment]
Hello Rituraj
If possible, please write about yourself so that we can get to know you better. What skills do you have?
Are you a UI designer? Can you design the site of this project?

**Comment by riturajjain2000** [comment]
I’m a Junior pursuing my B.Tech in Computer Science. I am having 2 years of hands-on experience in developing Android apps. Also, I work with Unity and have developed some fun Indie-games.
I love contributing to FOSS and have contributed majorly to UCSC,ODK-X and Oppia in the last few months along with minor fixes for Fossasia , NVIDIA and am a part of 35+ different communities on Github.

I mostly design UI's for Mobile Apps , still if you want I can give it a try sir!
