### ISSUE TITLE
ONE LANGUAGE DockerHub repository

### ISSUE THREAD

**Issue by abdorah** [One-Language/One#208]
Hello everyone!
Since I created the first version of our docker repository I will give you a full description of our goal and our ideas related to this topic.
The docker repository was created by a [GitHub workflow](https://github.com/abdorah/One/blob/master/.github/workflows/docker-image.yml) (this is the first attempt and can be changed later).

## What we need for the docker repository
1. The first important thing is that the image is going to be updated automatically using Github actions, so we need to find a method to set up a version of docker images.
2. We will need a README.md file also, I am excited to hear your ideas about this file. Yet, I think it needs essentially a good description of our project, how to use it, and something like the following part (How to use the docker image as a workspace (with VSCode)).

## How to use the docker image as a workspace (with VSCode)
 You can pull the [image](https://hub.docker.com/r/kotbionelang/one) directly which contains the setup development environment ( contains git and LLVM ...) with the entire `ONE` code. So you can use the image directly for development. I use VSCode for development so I will show you how to use it with the image. To do so, you will need [Visual Studio Code Remote Development](https://github.com/Microsoft/vscode-remote-release). After running your container, you can work from within the container:
1. run the container
![image](https://user-images.githubusercontent.com/37270435/127685518-84d90537-6c1e-4e25-be4c-ffbc4123e35c.png)
2. connect to the container
![Screenshot from 2021-07-30 17-47-28](https://user-images.githubusercontent.com/37270435/127685616-0237494b-8cb6-48e8-9aec-764e25a70577.png)
3. Now you can work from within the docker container and the previous step will open this new VSCode window
![Screenshot from 2021-07-30 17-50-53](https://user-images.githubusercontent.com/37270435/127685983-3fcb3c3f-15c0-4f64-9376-40e8fb176518.png)
4. Choose `One` directory
![Screenshot from 2021-07-30 17-52-25](https://user-images.githubusercontent.com/37270435/127686121-9e04d137-0cbb-45c8-815c-f339a21bc623.png)
5. finally here you go!
![Screenshot from 2021-07-30 17-53-15](https://user-images.githubusercontent.com/37270435/127686195-47d8cae2-9703-4da0-849e-dfc604d31598.png)

**Comment by abdorah** [comment]
Hello everyone! this is the first version of our docker hub readme.md file:

https://github.com/One-Language/One/blob/master/README_DOCKER.md
in docker hub

https://hub.docker.com/r/onelangorg/one

**Comment by BaseMax** [comment]
Thank you so much. **^_^**
