### ISSUE TITLE
Using shell variables in build.sh of the test stage

### ISSUE THREAD

**Issue by BaseMax** [One-Language/One#216]
As you know it's better for example: to get `clang` from  the **CC** variable.
and not repeat other arguments and flags.
We can put requirements file paths into a variable to make the build.sh, file shorter.

**Comment by mohitsaxenaknoldus** [comment]
Please assign it to me. Can you also provide path to the concerned file.

**Comment by BaseMax** [comment]
Sure, You are welcome.

https://github.com/One-Language/One/blob/master/test/build.sh

**Comment by mohitsaxenaknoldus** [comment]
> Sure, You are welcome.
> 
> https://github.com/One-Language/One/blob/master/test/build.sh

Ok so you want to variabalize clang using the CC variable? Where is this CC variable? Or do you want it to be created? 
And by requirements file paths do you mean all those paths being passed to the command?

**Comment by BaseMax** [comment]
I just want the commands and phrases that are repetitive not to be repeated and to use the variable.

```
CC=clang
FLAGS=...
OTHER_VARIABLES....
....
```

**Comment by mohitsaxenaknoldus** [comment]
ok got it now! I will create a PR soon.

**Comment by mohitsaxenaknoldus** [comment]
Opened PR: https://github.com/One-Language/One/pull/220 
@BaseMax Please take a look.
