### ISSUE TITLE
Link French language to the other README files

### ISSUE THREAD

**Issue by BaseMax** [One-Language/One#221]
For example:
- https://github.com/One-Language/One/blob/master/README.md
- https://github.com/One-Language/One/blob/master/README_AR.md
- .......

**Comment by mohitsaxenaknoldus** [comment]
Assign it to me, please. I'll do it.

**Comment by BaseMax** [comment]
Thanks, Sure. welcome.

I am looking forward your PR.

**Comment by mohitsaxenaknoldus** [comment]
PR raised: https://github.com/One-Language/One/pull/222
@BaseMax
