### ISSUE TITLE
🦮 Update CONTRIBUTING.md 🦮

### ISSUE THREAD

**Issue by jbampton** [One-Language/One#24]

**Comment by n4i9kita** [comment]
@jbampton  is this resolved or can I do it ?

**Comment by jbampton** [comment]
Hey @n4i9kita you can fix this

**Comment by jbampton** [comment]
Hey @BaseMax  I am doing this now my way.  No more manual and total automation

**Comment by jbampton** [comment]
Done now.  Thanks everyone 💯
