### ISSUE TITLE
🩱 Hacktoberfest 2021 - First 20 Win🩱

### ISSUE THREAD

**Issue by jbampton** [One-Language/One#260]
The first 20 merged win.

All 20 get some stickers.

Top ten get a t-shirt.

**Comment by BaseMax** [comment]
Thanks, Happy to all ^_^

**Comment by BaseMax** [comment]
**2021** finished and now going plan for **2022**.
We will create another new issue for the 2022 prizes.

Best wishes for everyone who involved in **One** project.

Happy coding! ^_^
M.

**Comment by BaseMax** [comment]
Going for 2022.
