### ISSUE TITLE
Fix grammar

### ISSUE THREAD

**Issue by jbampton** [One-Language/One#27]

**Comment by BaseMax** [comment]
If someone is Native at English, it's your chance to fix grammar and typo problems at `grammar.BNF` file.

**Comment by BaseMax** [comment]
@n4i9kita, You can solve this issue now?

**Comment by n4i9kita** [comment]
Yes, I am trying it now.
If I can, I will inform you.

**Comment by n4i9kita** [comment]
Can you please explain what [this](https://github.com/One-Language/One/blob/d01620a9050967f5791e64eb6f9230feeb2cb518/grammar.BNF#L3) means ? 
Is it that '``` it is not required for small programs and runnable scripts ```' ?

**Comment by BaseMax** [comment]
Sorry for the delay. Can you link to the line you mentioned?
I don't know are you talk about which line.

**Comment by BaseMax** [comment]
Line 3? https://github.com/One-Language/One/blob/master/grammar.BNF#L3

**Comment by n4i9kita** [comment]
yes

**Comment by BaseMax** [comment]
Usually when someone want to create a library and package, we have to define package name at first line of main file. 

```
package main
```

But generally, we not need to define package.

So it is only used when you want to design a library or package.

**Comment by n4i9kita** [comment]
Ok. Thanks for explaining.

**Comment by n4i9kita** [comment]
In [line 33](https://github.com/One-Language/One/blob/d01620a9050967f5791e64eb6f9230feeb2cb518/grammar.BNF#L33), [line 56](https://github.com/One-Language/One/blob/d01620a9050967f5791e64eb6f9230feeb2cb518/grammar.BNF#L56) and [line 85](https://github.com/One-Language/One/blob/d01620a9050967f5791e64eb6f9230feeb2cb518/grammar.BNF#L85),does  the <<b>second term</b>>  has 's' because of syntax or it is a grammatical mistake ?
Line 33 -
```<function_arguments> ::= <function_arguments> "," <function_argument>```
Shoudn't it be ?
```<function_arguments> ::= <function_argument> "," <function_argument>```

Please confirm.

**Comment by BaseMax** [comment]
`function_arguments` is not `function_argument`

> <***> it's BNF name and not English word.

They are name/key of BNF grammar. not english.

**Comment by BaseMax** [comment]
Just to be clear: if you change keys name, so you have to do for all other place where called that key name.

**Comment by n4i9kita** [comment]
There were 2-3 spelling errors in the key names. I have just corrected that.

**Comment by BaseMax** [comment]
Thanks Nikita.

**Comment by n4i9kita** [comment]
Please review the pr.
Also, can I work on some other issue now ?

**Comment by BaseMax** [comment]
Thanks, done.

>  Also, can I work on some other issue now ?

Yes; Are you a programmer? can you introduce yourself too?

**Comment by n4i9kita** [comment]
Yes.
 I am pursuing my BTech in Computer Science and Eng. at IIT Varanasi, India. I have completed my 2nd yr at college a few days back, and that's when I started with Open Source Contributions. I made my first contribution to Sympy      ( library in python), and 2nd one is yours. :)
I think, I am proficient in C++ and Python and have majorly worked with these two, and am familiar with C, Kotlin and Flutter.

**Comment by BaseMax** [comment]
Invitation send. welcome.

**Comment by BaseMax** [comment]
If you would like to help to Mission Statement. it's really very good. https://github.com/One-Language/One/issues/30
After that, we can work together on core and technical part. @n4i9kita

**Comment by n4i9kita** [comment]
Sorry for the delay.
I read #30 . 
Yes, I would like to help  as much as I can.
