### ISSUE TITLE
🔥 Docker Hub login 🔥

### ISSUE THREAD

**Issue by jbampton** [One-Language/One#278]
**Describe the bug**
GitHub Action fails for Docker

**To Reproduce**
Open a PR

**Expected behavior**
Tests pass green

**Screenshots**
<img width="453" alt="Screen Shot 2021-12-27 at 11 52 09 pm" src="https://user-images.githubusercontent.com/418747/147478222-41448e59-6169-4603-ab14-bc82a572e2df.png">

**Additional context**
Do we need a bot account to log into Docker ?

**Comment by jbampton** [comment]
I think we don't need this one on PR only on merge to `main`

**Comment by jbampton** [comment]
Fixed by #279

**Comment by BaseMax** [comment]
One user of community created docker hub account. If you need to access it we can tag him.
