### ISSUE TITLE
🕴️ Rename `master` branch to `main` 🕴️

### ISSUE THREAD

**Issue by jbampton** [One-Language/One#280]

**Comment by BaseMax** [comment]
# I agree, thanks

**Comment by mohitsaxenaknoldus** [comment]
Can I work on this?

**Comment by BaseMax** [comment]
> Can I work on this?

Yeah welcome ☺️

**Comment by mohitsaxenaknoldus** [comment]
Have we already changed the default branch to `main` in the settings?

**Comment by BaseMax** [comment]
> Have we already changed the default branch to `main` in the settings?

Good morning.
No, first we need to clone master branch into `main` branch.
next we can remove master branch and setting the default branch to `main`.

Best,
M.

**Comment by BaseMax** [comment]
Now the branch moved. So now it's Okay in your mind?

**Comment by mohitsaxenaknoldus** [comment]
I guess it's already done by now.

**Comment by jbampton** [comment]
Done now.  Thanks everyone !!
