### ISSUE TITLE
🧪 Check Markdown links 🧪

### ISSUE THREAD

**Issue by jbampton** [One-Language/One#288]
**Is your feature request related to a problem? Please describe.**
I hate broken links

**Describe the solution you'd like**
No broken links in all `One` repos

**Describe alternatives you've considered**
Manual checking or post production link scanners

**Additional context**
Use the GitHub Marketplace tools or Actions

https://github.com/marketplace?type=&verification=&query=check+markdown+links+

**Comment by jbampton** [comment]
https://github.com/marketplace/actions/markdown-link-check

**Comment by BaseMax** [comment]
What do you mean by broken line? EOF line?

**Comment by jbampton** [comment]
Not broken lines but broken `links` or hyperlinks in the Markdown files

**Comment by jbampton** [comment]
Done now 🥇
