### ISSUE TITLE
Korean translation

### ISSUE THREAD

**Issue by BaseMax** [One-Language/One#382]
Hi, good first issue

**Comment by BaseMax** [comment]
Maybe @Yaminyam is interested.

**Comment by Yaminyam** [comment]
I'm interested in that contribution! What can I do?

**Comment by BaseMax** [comment]
We have a README.md file. Would you translate that?

**Comment by BaseMax** [comment]
Other languages are inside the `langs` directory. You can take a look on other languages: https://github.com/One-Language/One/tree/main/langs
