### ISSUE TITLE
How can I get involved?

### ISSUE THREAD

**Issue by dev7060** [One-Language/One#4]
Hey everyone, if you have a slack channel or something for discussion, I would appreciate an invitation. I had a look at this project and it seems quite fascinating to me

**Comment by BaseMax** [comment]
Hi sir;
We have a discord server, @jbampton will give you invite link.
Thanks

**Comment by jbampton** [comment]
Hello @dev7060  here is our Discord Server link:

https://discord.gg/sFCE2HcMCa

Come and chat with our team :)

**Comment by dev7060** [comment]
ty
