### ISSUE TITLE
Adding One twitter at the README

### ISSUE THREAD

**Issue by BaseMax** [One-Language/One#40]
Hey friends;

Currenly my twitter account linked to README.
We need to change to to the official team twitter account.

I'm looking for twitter username...

**Comment by jbampton** [comment]
https://twitter.com/onelangteam

**Comment by BaseMax** [comment]
Thanks, Solved.

Now we need discord badges.

I'm looking: https://shields.io/category/social

**Comment by jbampton** [comment]
https://shields.io/category/chat

**Comment by BaseMax** [comment]
What's our serverId?

**Comment by BaseMax** [comment]
discord invite link is: https://discord.gg/sFCE2HcMCa

**Comment by BaseMax** [comment]
Thanks;
Please change line `[DiscordBadge]: https://img.shields.io/discord/592103645835821068?label=Discord&logo=discord&logoColor=white` at README.Md

**Comment by BaseMax** [comment]
Thanks JOhn;
