### ISSUE TITLE
📱 We can add other social account INSTA, FB to README 📱

### ISSUE THREAD

**Issue by BaseMax** [One-Language/One#41]
Pages:

- https://www.instagram.com/one.lang/
- https://www.facebook.com/onelangteam

We need Image badges.

**Comment by BaseMax** [comment]
Hey, we need to add these badges to README.

**Comment by abdorah** [comment]
**We can do something like this:**

<a href="https://www.instagram.com/one.lang/">
<img align="left"  width="22px" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Instagram_icon.png/600px-Instagram_icon.png" />
</a>
<a href="https://www.facebook.com/onelangteam">
 <img align="left"  width="22px" src="https://facebookbrand.com/wp-content/uploads/2019/04/f_logo_RGB-Hex-Blue_512.png?w=512&h=512" />
</a>

---

**using this :**
```
<a href="https://www.instagram.com/one.lang/">
<img align="left"  width="22px" src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Instagram_icon.png/600px-Instagram_icon.png" />
</a>
<a href="https://www.facebook.com/onelangteam">
 <img align="left"  width="22px" src="https://facebookbrand.com/wp-content/uploads/2019/04/f_logo_RGB-Hex-Blue_512.png?w=512&h=512" />
</a>
```

**Comment by jbampton** [comment]
Done
