### ISSUE TITLE
🔗 We need a much better link for "Getting Started" 🔗

### ISSUE THREAD

**Issue by jbampton** [One-Language/One#421]
Perhaps link to the Document site ?

Currently links to: https://github.com/One-Language/One/wiki

<img width="602" alt="Screen Shot 2022-11-29 at 5 09 00 am" src="https://user-images.githubusercontent.com/418747/204360921-531b8890-a462-44e3-91a3-c29aebb81827.png">

**Comment by Gokul2003g** [comment]
Please check the changes and approve. Thanks.

**Comment by jbampton** [comment]
Thank you. Done
