### ISSUE TITLE
We need to update `CONTRIBUTORS.md`

### ISSUE THREAD

**Issue by jbampton** [One-Language/One#469]
https://github.com/One-Language/One/blob/main/CONTRIBUTORS.md

**Comment by SNikhill** [comment]
@jbampton 
Is there a way I can help with this one?

**Comment by jbampton** [comment]
We should remove the "optimize" and "syntax" sections.

Remove all references to "all-contributors" bot

**Comment by jbampton** [comment]
Update the title at the top of the page and the copyright year at the bottom

**Comment by jbampton** [comment]
@BaseMax what do you think ?

**Comment by jbampton** [comment]
Done now :)
