### ISSUE TITLE
📠 Code scanning results / CodeQL Completed in 4s — 1 analysis not found.  What does this mean ?? 📠

### ISSUE THREAD

**Issue by jbampton** [One-Language/One#51]

**Comment by BaseMax** [comment]
John, can you explain where you got that text? We not have that in the project.

**Comment by BaseMax** [comment]
https://securitylab.github.com/tools/codeql/

**Comment by jbampton** [comment]
It happens on pull requests.  I added CodeQL for Javascript.

<img width="1290" alt="Screen Shot 2021-05-28 at 7 27 59 pm" src="https://user-images.githubusercontent.com/418747/119963080-08282300-bfeb-11eb-89dd-1c57c2ee8fa2.png">

**Comment by jbampton** [comment]
https://github.com/One-Language/One/blob/master/.github/workflows/codeql-analysis.yml

**Comment by jbampton** [comment]
Have not seen this for a while. Closing now
