### ISSUE TITLE
🛍️ Add GitHub Sponsors with Open Collective 🛍️

### ISSUE THREAD

**Issue by jbampton** [One-Language/One#56]

**Comment by BaseMax** [comment]
Mostly done we need to wait for the response of the Sponsors team at GitHub...
Thanks John;

**Comment by BaseMax** [comment]
We are still waiting for the GitHub sponsor team, Probably we will get this soon...

**Comment by BaseMax** [comment]
### You've been approved for GitHub Sponsors

Your GitHub Sponsors profile is live.

![Screenshot_2021-06-09_15-54-49](https://user-images.githubusercontent.com/2658040/121346193-0a6b7500-c93b-11eb-86ec-1521efcbe7d9.png)

**Comment by BaseMax** [comment]
Hooray! :+1: 
https://github.com/sponsors/One-Language
