### ISSUE TITLE
Remove the CLION editor settings from Git

### ISSUE THREAD

**Issue by jbampton** [One-Language/One#61]
The `.idea` folder is not meant to be committed it is your own editor specific files.

You should add the `.idea` folder to your global `gitignore`.

https://docs.github.com/en/github/getting-started-with-github/getting-started-with-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer

<img width="893" alt="Screen Shot 2021-05-29 at 5 41 00 am" src="https://user-images.githubusercontent.com/418747/120035300-b19a0380-c041-11eb-9ddc-2c9fec7ff3c0.png">

![Screen Shot 2021-05-29 at 5 45 44 am](https://user-images.githubusercontent.com/418747/120035361-d42c1c80-c041-11eb-94e1-ccceb81e9110.png)

**Comment by BaseMax** [comment]
Done: https://github.com/One-Language/One/commit/148352b65c65f12e66cdd1b14da781b5b4ef2dc9

**Comment by jbampton** [comment]
Yes we need the `.clang-format` file :)
