### ISSUE TITLE
Improve ISSUE Template

### ISSUE THREAD

**Issue by BaseMax** [One-Language/One#66]
Can someone please check template text and improve text / modify and fix Grammar mistakes?

If you have a suggestion or comment, please include it in the text or add a question if you think it is necessary.

https://github.com/One-Language/One/tree/master/.github/ISSUE_TEMPLATE

**Comment by BaseMax** [comment]
Dear John, please tag @tHe_AK for this one. @jbampton

**Comment by BaseMax** [comment]
#### A new tempalte

Also, I think we need another template for documentation writer and translated.

We have to ask about the English skills, or also other languages they know and good at.

And also we need to ask about their technical computer knowledge. 
Since maybe a person is a writer and not have much information about Programming and/or IT.

**Comment by tHe-AK** [comment]
> #### A new template
> Also, I think we need another template for documentation writer and translated.
> 
> We have to ask about the English skills, or also other languages they know and good at.
> 
> And also we need to ask about their technical computer knowledge.
> Since maybe a person is a writer and not have much information about Programming and/or IT.

Got it, Let me formulate some template first then you can have a look for finalizing it.

**Comment by BaseMax** [comment]
No update? I would like to see your PR. @tHe-AK
