### ISSUE TITLE
🩱 `One` will be in Hacktoberfest 2021 🩱

### ISSUE THREAD

**Issue by jbampton** [One-Language/One#81]
`One` will be offering prizes in October for Hacktoberfest 😎

I think we could easily do the first 50 merged into `One` in October WIN !!!

I can cover the costs of cool stickers and postage all over the world 🚀🚀🚀🚀🚀🚀🚀🚀

I've started this conversation let's all really keep it going and come up with some awesome ideas 🍓 🌶️ 🥩 🦪 🎂 🍾

https://hacktoberfest.digitalocean.com/

**Comment by BaseMax** [comment]
"117d 23h 12m 8s" https://hacktoberfest.digitalocean.com/

Okay John, Let us ready with power. :+1:

**Comment by jbampton** [comment]
https://hacktoberfestswaglist.com/  🩱🩱🩱🩱🩱🩱🩱🩱🩱🩱🩱🩱

<img width="930" alt="Screen Shot 2021-06-05 at 7 20 43 am" src="https://user-images.githubusercontent.com/418747/120864056-f20ff900-c5ce-11eb-9fa3-31890212ee19.png">

**Comment by BaseMax** [comment]
**87d 20h 9m 46s**

Time is passing sooner than we think.
And we are very slow.

**Comment by jbampton** [comment]
@basalumutgazi  was going to help with this

**Comment by BaseMax** [comment]
**64d 19h 20m 43s**

^_^ We are going...

**Comment by BaseMax** [comment]
**36d 7h 23m 15s**

I am a little worried because we are also involved in the festival.

**Comment by BaseMax** [comment]
https://github.com/One-Language/One/issues/260
